### ISSUE TITLE
WARNING: Duplicate symbol

### ISSUE THREAD

**Issue by isidentical** [aixtools/pythonAIXDOC#1]
I followed the guide and configured the build with these parameters (`xlc_r` wasn't on the system, so I used `xlc`)
```
-bash-4.4$ CC=xlc OPT="-O2 -qmaxmem=-1" ./configure --without-computed-gotos -C
```
and then did a `make -j60`, the logs are here and most of them look like this. I have no idea why it is throwing them (used `upstream/master`)

```
ld: 0711-224 WARNING: Duplicate symbol: _PyUnicode_Ready
ld: 0711-224 WARNING: Duplicate symbol: ._PyArg_ParseTupleAndKeywords_SizeT
ld: 0711-224 WARNING: Duplicate symbol: _PyArg_ParseTupleAndKeywords_SizeT
ld: 0711-224 WARNING: Duplicate symbol: ._PyTime_FromSecondsObject
ld: 0711-224 WARNING: Duplicate symbol: _PyTime_FromSecondsObject
ld: 0711-224 WARNING: Duplicate symbol: ._PyTime_AsMilliseconds
ld: 0711-224 WARNING: Duplicate symbol: _PyTime_AsMilliseconds
ld: 0711-224 WARNING: Duplicate symbol: .PyErr_Format
ld: 0711-224 WARNING: Duplicate symbol: PyErr_Format
ld: 0711-224 WARNING: Duplicate symbol: ._PyObject_CallFunction_SizeT
ld: 0711-224 WARNING: Duplicate symbol: _PyObject_CallFunction_SizeT
ld: 0711-224 WARNING: Duplicate symbol: PyExc_ValueError
ld: 0711-224 WARNING: Duplicate symbol: .PyImport_ImportModule
ld: 0711-224 WARNING: Duplicate symbol: PyImport_ImportModule
ld: 0711-224 WARNING: Duplicate symbol: .PyModule_GetDict
ld: 0711-224 WARNING: Duplicate symbol: PyModule_GetDict
ld: 0711-224 WARNING: Duplicate symbol: ._PyDict_GetItemIdWithError
ld: 0711-224 WARNING: Duplicate symbol: _PyDict_GetItemIdWithError
ld: 0711-224 WARNING: Duplicate symbol: .PyGILState_Ensure
ld: 0711-224 WARNING: Duplicate symbol: PyGILState_Ensure
ld: 0711-224 WARNING: Duplicate symbol: .PyGILState_Release
ld: 0711-224 WARNING: Duplicate symbol: PyGILState_Release
ld: 0711-224 WARNING: Duplicate symbol: .PyUnicode_FromStringAndSize
ld: 0711-224 WARNING: Duplicate symbol: PyUnicode_FromStringAndSize
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_CallFunctionObjArgs
ld: 0711-224 WARNING: Duplicate symbol: PyObject_CallFunctionObjArgs
ld: 0711-224 WARNING: Duplicate symbol: .PyLong_AsLongAndOverflow
ld: 0711-224 WARNING: Duplicate symbol: PyLong_AsLongAndOverflow
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_GetAttrString
ld: 0711-224 WARNING: Duplicate symbol: PyObject_GetAttrString
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_CallObject
ld: 0711-224 WARNING: Duplicate symbol: PyObject_CallObject
ld: 0711-224 WARNING: Duplicate symbol: PyTuple_Type
ld: 0711-224 WARNING: Duplicate symbol: PyList_Type
ld: 0711-224 WARNING: Duplicate symbol: PyDict_Type
ld: 0711-224 WARNING: Duplicate symbol: PyLong_Type
ld: 0711-224 WARNING: Duplicate symbol: PyFloat_Type
ld: 0711-224 WARNING: Duplicate symbol: PyByteArray_Type
ld: 0711-224 WARNING: Duplicate symbol: .PyUnicode_FromString
ld: 0711-224 WARNING: Duplicate symbol: PyUnicode_FromString
ld: 0711-224 WARNING: Duplicate symbol: PyExc_LookupError
ld: 0711-224 WARNING: Duplicate symbol: .PySequence_Check
ld: 0711-224 WARNING: Duplicate symbol: PySequence_Check
ld: 0711-224 WARNING: Duplicate symbol: .PySequence_GetItem
ld: 0711-224 WARNING: Duplicate symbol: PySequence_GetItem
ld: 0711-224 WARNING: Duplicate symbol: .PySequence_Size
ld: 0711-224 WARNING: Duplicate symbol: PySequence_Size
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_GetBuffer
ld: 0711-224 WARNING: Duplicate symbol: PyObject_GetBuffer
ld: 0711-224 WARNING: Duplicate symbol: .PyBuffer_Release
ld: 0711-224 WARNING: Duplicate symbol: PyBuffer_Release
ld: 0711-224 WARNING: Duplicate symbol: .PyFloat_AsDouble
ld: 0711-224 WARNING: Duplicate symbol: PyFloat_AsDouble
ld: 0711-224 WARNING: Duplicate symbol: .PyUnicode_AsUTF8AndSize
ld: 0711-224 WARNING: Duplicate symbol: PyUnicode_AsUTF8AndSize
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_ClearWeakRefs
ld: 0711-224 WARNING: Duplicate symbol: PyObject_ClearWeakRefs
ld: 0711-224 WARNING: Duplicate symbol: .PyOS_mystrnicmp
ld: 0711-224 WARNING: Duplicate symbol: PyOS_mystrnicmp
ld: 0711-224 WARNING: Duplicate symbol: ._PyObject_New
ld: 0711-224 WARNING: Duplicate symbol: _PyObject_New
ld: 0711-224 WARNING: Duplicate symbol: .PyWeakref_NewRef
ld: 0711-224 WARNING: Duplicate symbol: PyWeakref_NewRef
ld: 0711-224 WARNING: Duplicate symbol: ._PyArg_NoKeywords
ld: 0711-224 WARNING: Duplicate symbol: _PyArg_NoKeywords
ld: 0711-224 WARNING: Duplicate symbol: _Py_TrueStruct
ld: 0711-224 WARNING: Duplicate symbol: ._Py_BuildValue_SizeT
ld: 0711-224 WARNING: Duplicate symbol: _Py_BuildValue_SizeT
ld: 0711-224 WARNING: Duplicate symbol: .PyUnicode_DecodeUTF8
ld: 0711-224 WARNING: Duplicate symbol: PyUnicode_DecodeUTF8
ld: 0711-224 WARNING: Duplicate symbol: .PyErr_Print
ld: 0711-224 WARNING: Duplicate symbol: PyErr_Print
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_IsTrue
ld: 0711-224 WARNING: Duplicate symbol: PyObject_IsTrue
ld: 0711-224 WARNING: Duplicate symbol: ._PyLong_AsInt
ld: 0711-224 WARNING: Duplicate symbol: _PyLong_AsInt
ld: 0711-224 WARNING: Duplicate symbol: .PyErr_Fetch
ld: 0711-224 WARNING: Duplicate symbol: PyErr_Fetch
ld: 0711-224 WARNING: Duplicate symbol: .PyErr_Restore
ld: 0711-224 WARNING: Duplicate symbol: PyErr_Restore
ld: 0711-224 WARNING: Duplicate symbol: .PyTuple_New
ld: 0711-224 WARNING: Duplicate symbol: PyTuple_New
ld: 0711-224 WARNING: Duplicate symbol: .PyTuple_SetItem
ld: 0711-224 WARNING: Duplicate symbol: PyTuple_SetItem
ld: 0711-224 WARNING: Duplicate symbol: .PyFloat_FromDouble
ld: 0711-224 WARNING: Duplicate symbol: PyFloat_FromDouble
ld: 0711-224 WARNING: Duplicate symbol: .PyLong_FromLongLong
ld: 0711-224 WARNING: Duplicate symbol: PyLong_FromLongLong
ld: 0711-224 WARNING: Duplicate symbol: .PyBytes_FromStringAndSize
ld: 0711-224 WARNING: Duplicate symbol: PyBytes_FromStringAndSize
ld: 0711-224 WARNING: Duplicate symbol: .PyList_Size
ld: 0711-224 WARNING: Duplicate symbol: PyList_Size
ld: 0711-224 WARNING: Duplicate symbol: .PyList_GetItem
ld: 0711-224 WARNING: Duplicate symbol: PyList_GetItem
ld: 0711-224 WARNING: Duplicate symbol: .PyWeakref_GetObject
ld: 0711-224 WARNING: Duplicate symbol: PyWeakref_GetObject
ld: 0711-224 WARNING: Duplicate symbol: ._PyUnicode_EqualToASCIIString
ld: 0711-224 WARNING: Duplicate symbol: _PyUnicode_EqualToASCIIString
ld: 0711-224 WARNING: Duplicate symbol: PyExc_AttributeError
ld: 0711-224 WARNING: Duplicate symbol: PyUnicode_FSConverter
ld: 0711-224 WARNING: Duplicate symbol: .PyBytes_AsString
ld: 0711-224 WARNING: Duplicate symbol: PyBytes_AsString
ld: 0711-224 WARNING: Duplicate symbol: .PyUnicode_FromFormat
ld: 0711-224 WARNING: Duplicate symbol: PyUnicode_FromFormat
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_Print
ld: 0711-224 WARNING: Duplicate symbol: PyObject_Print
ld: 0711-224 WARNING: Duplicate symbol: .PyThread_get_thread_ident
ld: 0711-224 WARNING: Duplicate symbol: PyThread_get_thread_ident
ld: 0711-224 WARNING: Duplicate symbol: _PyObject_NextNotImplemented
ld: 0711-224 WARNING: Duplicate symbol: .PyIter_Next
ld: 0711-224 WARNING: Duplicate symbol: PyIter_Next
ld: 0711-224 WARNING: Duplicate symbol: ._PyErr_FormatFromCause
ld: 0711-224 WARNING: Duplicate symbol: _PyErr_FormatFromCause
ld: 0711-224 WARNING: Duplicate symbol: PyExc_UnicodeDecodeError
ld: 0711-224 WARNING: Duplicate symbol: PyBytes_Type
ld: 0711-224 WARNING: Duplicate symbol: .PyByteArray_FromStringAndSize
ld: 0711-224 WARNING: Duplicate symbol: PyByteArray_FromStringAndSize
ld: 0711-224 WARNING: Duplicate symbol: .PyOS_snprintf
ld: 0711-224 WARNING: Duplicate symbol: PyOS_snprintf
ld: 0711-224 WARNING: Duplicate symbol: .PyUnicode_Decode
ld: 0711-224 WARNING: Duplicate symbol: PyUnicode_Decode
ld: 0711-224 WARNING: Duplicate symbol: .PyErr_SetObject
ld: 0711-224 WARNING: Duplicate symbol: PyErr_SetObject
ld: 0711-224 WARNING: Duplicate symbol: PyObject_SelfIter
ld: 0711-224 WARNING: Duplicate symbol: .PyModule_AddObject
ld: 0711-224 WARNING: Duplicate symbol: PyModule_AddObject
ld: 0711-224 WARNING: Duplicate symbol: PyExc_ImportError
ld: 0711-224 WARNING: Duplicate symbol: PyExc_Exception
ld: 0711-224 WARNING: Duplicate symbol: .PyErr_NewException
ld: 0711-224 WARNING: Duplicate symbol: PyErr_NewException
ld: 0711-224 WARNING: Duplicate symbol: .PyLong_FromLong
ld: 0711-224 WARNING: Duplicate symbol: PyLong_FromLong
ld: 0711-224 WARNING: Duplicate symbol: .PySys_Audit
ld: 0711-224 WARNING: Duplicate symbol: PySys_Audit
ld: 0711-224 WARNING: Duplicate symbol: .PyObject_Call
ld: 0711-224 WARNING: Duplicate symbol: PyObject_Call
```

[logs.txt](https://github.com/aixtools/pythonAIXDOC/files/4411725/logs.txt)

**Comment by aixtools** [comment]
My guess is that xlc is a symbolic link to a directory where you will
find xlc_r.

I have the following - to switch between versions:

$ head *env
==> xlc13-env <==
#!/usr/bin/ksh -e

export PATH=/opt/IBM/xlc/13.1.3/bin:${PATH}

export CC=xlc_r

==> xlc16-env <==
#!/usr/bin/ksh -e

export PATH=/opt/IBM/xlc/16.1.0/bin:${PATH}

export CC=xlc_r

Further, most of the duplicate symbol messages from below are a
side-effect of the way AIX .so files are created when using even -j2 for
the make command.

Due to the way some external OSS packages were created - some duplicate
messages may still show up - even with -j1.

**Comment by isidentical** [comment]
>My guess is that xlc is a symbolic link to a directory where you will
find xlc_r.

```
-bash-4.4$ whereis xlc
xlc: /usr/bin/xlc
-bash-4.4$ ls /usr/bin | grep xlc
xlc
```
No xlc_r :( 

> Further, most of the duplicate symbol messages from below are a
side-effect of the way AIX .so files are created when using even -j2 for
the make command.

Do you know a way to ignore them?

**Comment by aixtools** [comment]
To find where it is (/usr/bin is NOT standard!!) try:

lslpp -w | grep xlc_r

On the gccfarm server (gcc119) I see:

 lslpp -w | grep xlc_r | grep -v man
  /opt/IBM/xlc/13.1.3/bin/xlc_r4              xlccmp.13.1.3         Symlink
  /opt/IBM/xlc/13.1.3/bin/xlc_r7              xlccmp.13.1.3         Symlink
  /opt/IBM/xlc/13.1.3/bin/.orig/xlc_r4        xlccmp.13.1.3         Symlink
  /opt/IBM/xlc/13.1.3/bin/.orig/xlc_r7        xlccmp.13.1.3         Symlink
  /opt/IBM/xlc/13.1.3/bin/xlc_r               xlccmp.13.1.3         Symlink
  /opt/IBM/xlc/13.1.3/bin/.orig/xlc_r         xlccmp.13.1.3         Symlink
  /opt/IBM/xlC/13.1.3/bin/.orig/xlc_r         xlCcmp.13.1.3         Symlink
  /opt/IBM/xlC/13.1.3/bin/xlc_r4              xlCcmp.13.1.3         Symlink
  /opt/IBM/xlC/13.1.3/bin/xlc_r7              xlCcmp.13.1.3         Symlink
  /opt/IBM/xlC/13.1.3/bin/.orig/xlc_r4        xlCcmp.13.1.3         Symlink
  /opt/IBM/xlC/13.1.3/bin/.orig/xlc_r7        xlCcmp.13.1.3         Symlink
  /opt/IBM/xlC/13.1.3/bin/xlc_r               xlCcmp.13.1.3         Symlink
  /opt/IBM/xlc/16.1.0/bin/xlc_r               xlccmp.16.1.0         Symlink
  /opt/IBM/xlc/16.1.0/bin/.orig/xlc_r         xlccmp.16.1.0         Symlink
  /opt/IBM/xlc/16.1.0/bin/xlc_r4              xlccmp.16.1.0         Symlink
  /opt/IBM/xlc/16.1.0/bin/xlc_r7              xlccmp.16.1.0         Symlink
  /opt/IBM/xlc/16.1.0/bin/.orig/xlc_r4        xlccmp.16.1.0         Symlink
  /opt/IBM/xlc/16.1.0/bin/.orig/xlc_r7        xlccmp.16.1.0         Symlink
  /opt/IBM/xlC/16.1.0/bin/.orig/xlc_r4        xlCcmp.16.1.0         Symlink
  /opt/IBM/xlC/16.1.0/bin/.orig/xlc_r7        xlCcmp.16.1.0         Symlink
  /opt/IBM/xlC/16.1.0/bin/.orig/xlc_r         xlCcmp.16.1.0         Symlink
  /opt/IBM/xlC/16.1.0/bin/xlc_r               xlCcmp.16.1.0         Symlink
  /opt/IBM/xlC/16.1.0/bin/xlc_r4              xlCcmp.16.1.0         Symlink
  /opt/IBM/xlC/16.1.0/bin/xlc_r7              xlCcmp.16.1.0         Symlink

So the real directory is /opt/IBM/xl[cC]/13.1.3/bin for xlc v13, and
/opt/IBM/xl[cC]/16.1.0/bin for xlc v16.

For xlc v11 they are at /var/vac/bin and /var/vacpp/bin

On 08/04/2020 03:43, Batuhan Taşkaya wrote:
>
>     My guess is that xlc is a symbolic link to a directory where you will
>     find xlc_r.
>
> |-bash-4.4$ whereis xlc xlc: /usr/bin/xlc -bash-4.4$ ls /usr/bin |
> grep xlc xlc |
>
> No xlc_r :(
>
>     Further, most of the duplicate symbol messages from below are a
>     side-effect of the way AIX .so files are created when using even
>     -j2 for
>     the make command.
>
> Do you know a way to ignore them?
>
You may ignore them - however to eliminate them, most of them, by not
using -jX with make, at least not with Python. They add, afaik, extra
flags to export symbols - and they get exported over and over a and over
again - when built in parallel.

Not all - because some OSS packaging has duplicated the symbols - so
there message is "always" there.

**Comment by isidentical** [comment]
> On the gccfarm server (gcc119) I see:

Thanks, now I can also see them (I'm on the same machine). 

> You may ignore them - however to eliminate them, most of them, by not
using -jX with make, at least not with Python. They add, afaik, extra
flags to export symbols - and they get exported over and over a and over
again - when built in parallel.

I see :/ Thanks again for helping me

**Comment by aixtools** [comment]
Maybe you can find why xlc v13 and xlc v16 fail on this:

Failed to build these modules:
_decimal

due to:

xlc_r -O -I./Include/internal -DCONFIG_32=1 -DANSI=1
-I/home/aixtools/buildarea/3.x.aixtools-aix-power6/build/Modules/_decimal/libmpdec
-I./Include -I.
-I/home/aixtools/buildarea/3.x.aixtools-aix-power6/build/Include
-I/home/aixtools/buildarea/3.x.aixtools-aix-power6/build -c
/home/aixtools/buildarea/3.x.aixtools-aix-power6/build/Modules/_decimal/libmpdec/mpdecimal.c
-o
build/temp.aix-7200-1543-32-3.9-pydebug/home/aixtools/buildarea/3.x.aixtools-aix-power6/build/Modules/_decimal/libmpdec/mpdecimal.o
"/home/aixtools/buildarea/3.x.aixtools-aix-power6/build/Modules/_decimal/libmpdec/mpdecimal.c",
line 249.5: 1506-780 (S) Reference to "_mpd_idiv_word" with internal
linkage is not allowed within inline definition of "mpd_digits_to_size".


On 08/04/2020 14:17, Batuhan Taşkaya wrote:
>
>     On the gccfarm server (gcc119) I see:
>
> Thanks, now I can also see them (I'm on the same machine).
>
I thought you might be.

**Comment by isidentical** [comment]
> Maybe you can find why xlc v13 and xlc v16 fail on this:

Will check it out at tonight.
